# Generated by Django 3.1.2 on 2020-10-30 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=350)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(choices=[('RED', 'red'), ('BLU', 'blue'), ('YEL', 'yellow'), ('ORA', 'orange'), ('GRE', 'green'), ('PUR', 'purple'), ('BRO', 'brown'), ('FUX', 'fuxia')], default='yellow', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
